export enum ProductType {
    Cooking = 'Cooking',
    Cleaning = 'Cleaning',
    Tool = 'Tool',
    Fruit = 'Fruit',
    Vegetable = 'Vegetable',
    Meat = 'Meat',
    Dairy = 'Dairy',
    MilkAndEggs = 'MilkAndEggs',
    Furniture = 'Furniture',
    TV = 'TV',
    Laptop = 'Laptop',
    Phone = 'Phone',
    Microwave = 'Microwave',
    Stove = 'Stove',
    Art = 'Art',
    Pets = 'Pets',
    Carpets = 'Carpets',
    CarAccessory = 'CarAccessory',
    Decoration = 'Decoration',
    Fashion = 'Fashion',
    Clothing = 'Clothing',
    Perfume = 'Perfume',
    Lamp = 'Lamp',
    Toy = 'Toy',
    Food = 'Food',
    Other = 'Other'
  }
  